# Server Port
server.port=8080

# Application Name
spring.application.name=customer-support-service

# PostgreSQL Database Configuration
# Replace 'crm_db', 'postgres', and 'your_password' with your database setup
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_support
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Auto Table Creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect